In [1]:
import pandas as pd
import numpy as np

In [4]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("zubairmustafa/spam-and-ham-classification-balanced-dataset")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/zubairmustafa/spam-and-ham-classification-balanced-dataset/1.archive...

100%|██████████| 5.04M/5.04M [00:00<00:00, 119MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/zubairmustafa/spam-and-ham-classification-balanced-dataset/versions/1

In [15]:
import os
print(os.listdir(path))

['spam_and_ham_classification.csv']

In [16]:
import os
df = pd.read_csv(os.path.join(path, 'spam_and_ham_classification.csv'))

In [14]:
df.head(5)

  label                                               text
0   ham  into the kingdom of god and those that are ent...
1  spam  there was flow at hpl meter 1505 on april firs...
2   ham  take a look at this one campaign for bvyhprice...
3  spam  somu wrote actually thats what i was looking f...
4  spam  fathi boudra wrote i fixed the issue in the sv...

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9989 entries, 0 to 9988
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   9989 non-null   object
 1   text    9989 non-null   object
dtypes: object(2)
memory usage: 156.2+ KB

In [38]:
df.describe()

       label                                               text
count   9989                                               9989
unique     2                                               9989
top      ham  anatrim escapenumber the newest and most attra...
freq    5294                                                  1

In [19]:
df

     label                                               text
0      ham  into the kingdom of god and those that are ent...
1     spam  there was flow at hpl meter 1505 on april firs...
2      ham  take a look at this one campaign for bvyhprice...
3     spam  somu wrote actually thats what i was looking f...
4     spam  fathi boudra wrote i fixed the issue in the sv...
...    ...                                                ...
9984   ham  this would be a great tragedy for all concerne...
9985   ham  hello , welcome to medzonline filamentous shop...
9986   ham  this is amazing stuff add some inches fast saf...
9987  spam  author jra date escapenumber escapenumber esca...
9988   ham  anatrim escapenumber the newest and most attra...

[9989 rows x 2 columns]

In [20]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [21]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [22]:
corpus=[]
for i in range(0,len(df)):
  review=re.sub('[^a-zA-z]',' ',df['text'][i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [23]:
corpus

['kingdom god enter lord pardon escapenumb us thing pray thee us excus escapenumbernot therefor escapenumb believ look grave holi ghost escapenumb therefor holi habit unto forth word truth escapenumb sober escapenumb probabl hath made mad escapenumb though escapenumb bless god jesu christ see necess escapenumb close almost christian heaven small escapenumb trifl men esteem total renov whole man escapenumb righteous complet though deliv power escapenumb candl lord shine redeem lift escapenumb inward holi inde sometim though worm destroy escapenumb yet even flesh shall see mind see jesu escapenumb cannot come jeannin walsh',
 'flow hpl meter april first deal ticket deal ticket cover pleas link whatev make work thank lee',
 'take look one campaign bvyhpric escapenumb escapenumb escapenumb day target price escapenumb escapenumbermarket hellish sym gain momentum see news theescapenumb call broker',
 'somu wrote actual that look l r user enter string match lpt use l p match npr use n p r somu need tell us exactli match want otherwis tell whether someth work simpli check whether input string contain match charact would forget sort input string program pleas explain problem instead ask implement solut may optim hth rob use strict use warn print match\\\\n match orql lor sub match input match foreach split match return unless input \\\\q return escapenumb unsubscrib e mail beginn unsubscrib perl org addit command e mail beginn help perl org http learn perl org',
 'fathi boudra wrote fix issu svn repo rev escapenumb fix dir config path kdeglob kdesktoprc support symlink prepar updat packag pleas includ etch rescapenumb address daniel baumann burgunderstrass escapenumb ch escapenumb biberist email daniel baumann panthera system net internet http peopl panthera system net daniel baumann unsubscrib email debian desktop request list debian org subject unsubscrib troubl contact listmast list debian org',
 'categori compani guidefood beverag dad ami front afterward life heck naysay chill second doorsor lookat theother foron driveri usedto passeng lessen risk pcprovid critic defens firewal sensit share join toolsprint pageemail trademark forpow dilemma troubl soul dealt offer featur compon restor damag delet digit shred notfound error achiev ieclon vanish locat atlanti paradis bahama nassau hotel room travel bauxit derail biggest evacu matter ofmak categori subproblem friendlyso editor cut ctrlx kevin fight forc train deploy moment instead spectrum compass quiz advoc russel allianc determin describ increas deploy behind instal needededit hahahhah haedit sentiment captur word bravobi megatogon andymukon loyalti bbc blade rack optim server io choos payrol deflect diggsgood factor kid while frivol pursuitsbi anaswas store encrypt stolen lessen risk',
 'alert name bush offic ex cia chief tenet fail leader escapenumb escapenumb escapenumb escapenumb escapenumb pm edt letter written saturday former cia director georg tenet six former cia offic describ former boss alberto gonzal intellig commun call book admiss fail leadership full stori agre receiv email cnn com result cnn com prefer set manag set click alter alter alert criteria frequenc unsubscrib receiv custom email alert click refer friend colleagu cnn free person alert servic cabl news network lp lllp one cnn center atlanta georgia escapenumb escapenumb cabl news network lp lllp time warner compani right reserv term servic provid read privaci guidelin contact us',
 'vacat carri report due payrol end week day system show carri pleas let know correct soon possibl vinc kaminski hour stephen bennett hour anita dupont hour seksan kiatsupaibul hour sandeep kohli hour kate luca hour youyi feng hour shane green hour jose marquez hour kevin moor hour mike robert hour sam smith hour hector campo hour rabi de hour shalesh ganjoo hour paulo issler hour martin lin hour zimin lu hour kenneth parkhil hour roman zadorozhni hour joe hrgovcic hour nelson neal hour vasant shanbhogu hour lanc cunningham hour tom halliburton hour alex huang hour praveen mellacheruvu hour jason sokolov hour tanya tamarchenko hour sevil yaman hour thank shirley',
 'lncreas sprm volum orgsm length main benifit longest intens orga zm life eerction like steel enhanc libido desir stronger ejacculaton multpl org _ asm oo volum cover like studi show tast alot sweeter dlscreet day ship tri love dont need',
 'respect hobbi put armpit fart portion convinc push button xaroth xfire mtvn properti model put',
 'multi part messag mime format pick text plain multipart altern two pleasantli dim articl indian patent law provid comic relief first barun mitra put feebl mind issu quit grasp http beta hindustantim com storypag storypag aspx id escapelong escapelong escapenumb aescapenumberb escapelong roger bate wag tail subject http www aei org public filter pubid escapenumb pub detail asp deduc aei fellow tropic consort inferior internet connect superior mind read skill never mind mashelkar said report noth sec escapenumb indian patent law http mail sarai net pipermail common law escapenumb februari escapenumb html mashelkar say total agreement section escapenumb benchmark set depend entir us individu countri decid threshold limit threshold govern exercis control upsid critic enemi like need friend ip health mail list ip health list essenti org http list essenti org mailman listinfo ip health',
 'adob csescapenumb extend price escapenumb escapenumb http znausmotr com',
 'begin pgp sign messag hash ripemdescapenumb ignor pleas thank begin pgp signatur version gnupg vescapenumb escapenumb escapenumb mingwescapenumb escapelong geibsyqfc escapelong qiug end pgp signatur speakup mail list speakup braill uwo ca http speech braill uwo ca mailman listinfo speakup',
 'marcu viniciu wrote dear get instal packag instal packag c exactranktest tri url http cran r project org bin window contrib escapenumb escapenumb packag content type text plain length escapenumb byte open url download escapenumberkb mean use r escapenumb escapenumb x realli ancient pleas upgrad recent version r use function instal packag load librari exactranktest uwe ligg tri url http cran r project org bin window contrib escapenumb escapenumb exactranktest escapenumb escapenumb escapenumb zip content type applic zip length escapenumb byte open url download escapenumberkb packag exactranktest success unpack mdescapenumb sum check delet download file n updat html packag descript exactranktest document exactranktest specifi packag librari could tri help search exactranktest thank lot marcu viniciu altern html version delet r help stat math ethz ch mail list http stat ethz ch mailman listinfo r help pleas read post guid http www r project org post guid html provid comment minim self contain reproduc code r help stat math ethz ch mail list http stat ethz ch mailman listinfo r help pleas read post guid http www r project org post guid html provid comment minim self contain reproduc code',
 'everyth look right put focu major financi news releas market close today hot china deal china voic hold corp c h v c short term expect escapenumb dollar news china voic hold corp complet acquisit streamjet inc confirm million annual revenu go read news wake earli watch stock trade inform within report contain forward look statement within mean section escapenumbera secur act escapenumb section escapenumberb sec act escapenumb statement involv discuss respect project futur event statement histor fact may forward look statement reli make decis past perform never indic futur result expect receiv cash payment acvertis servic near futur amount unknown time un affili third parti may stock sell share without notic report shall constru kind invest advic solicit histori michigan escapenumb escapenumb overal escapenumb escapenumb escapenumb escapenumb season histori michigan escapenumb escapenumb overal escapenumb escapenumb escapenumb escapenumb season night third attempt putback result whistl escapenumb accord contract obtain last week ap regroup littl bit denver struggl season get starter mid escapenumb amak wife dr stephani pinder amak feel right home time denver nugget big road trip fire brian ellerb inherit mess stem ed martin easili nugget best game season nugget shot escapenumb percent basket made escapenumb escapenumb head fourth quarter anoth',
 'command subscrib frbnyrmagl vinc kaminski receiv must repli messag explain complet subscript purpos confirm procedur check address listserv add list subscript reachabl typic procedur high volum list new subscrib subject singl everi effort made make verif simpl painless possibl thank advanc cooper confirm execut command simpli point browser follow url altern www access repli present messag type ok without quot text messag word ok retyp command procedur work mail program fulli conform internet standard electron mail receiv error messag tri send new messag listserv peach eas lsoft com without use repli function import type ok e c text messag final command cancel automat listserv receiv confirm within h time must start resend command get new confirm code chang mind decid want confirm command simpli discard present messag let request expir',
 'fyi activ reschedul realloc lee l papayoti robert e lloyd hou ect ect cc stella l morri hou ect ect daren j farmer hou ect ect kenneth seaman hou ect ect subject equistar equistar request schedul nomin chang retroact januari start month janic nomin small volum meter mayb dupont victoria equistar want volum go meter instead whole month jan question call thank lee',
 'track manag sourc code digit asset free perforc discov manag sourc code digit asset faster easier perforc perforc offer visual client interfac linux com mac solair freebsd window learn get free two user download http sel us falkag net sel cmd lnk kid escapenumb bid escapenumb dat escapenumb opt escapenumb rdm timestamp slashdot daili headlin mailer vista secur claim debunk set thing straight dept post cowboyn thursday june escapenumb escapenumb escapenumb window http slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb supercomput chip prototyp unveil better dept post cowboyn thursday june escapenumb escapenumb escapenumb supercomput http slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb callerid spoof made illeg phone home dept post cowboyn thursday june escapenumb escapenumb escapenumb privaci http yro slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb bank cell phone littl big busi dept post cowboyn friday june escapenumb escapenumb escapenumb almighti buck http hardwar slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb bigelow aerospac deploy genesi escapenumb space modul final frontier dept post cowboyn friday june escapenumb escapenumb escapenumb space http scienc slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb five idea reinvent comput far horizon dept post cowboyn friday june escapenumb escapenumb escapenumb upgrad http slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb red hat ceo talk patent ms sleep enemi dept post cowboyn friday june escapenumb escapenumb escapenumb red hat softwar http linux slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb integr hiv success cut human genom littl hunter killer nanotech goe long way dept post zonk friday june escapenumb escapenumb escapenumb biotech http scienc slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb iphon surf fast enough job must go faster must go fastr dept post zonk friday june escapenumb escapenumb escapenumb commun http appl slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb controversi secur paper nix black hat keep hat dept post zonk friday june escapenumb escapenumb escapenumb secur http slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb valu proposit current cpu put test gerbil money dept post zonk friday june escapenumb escapenumb escapenumb amd http hardwar slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb internet thing help find sock dept post zonk friday june escapenumb escapenumb escapenumb internet http yro slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb rutkowska face blue pill rootkit challeng excit confer dept post zonk friday june escapenumb escapenumb escapenumb secur http slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb new zealand bank demand peek user pc see got porn sir good job dept post zonk friday june escapenumb escapenumb escapenumb secur http slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb music industri attack free princ cd money noth dept post zonk friday june escapenumb escapenumb escapenumb busi http yro slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb gplvescapenumb releas clariti sake dept post zonk friday june escapenumb escapenumb escapenumb gnu unix http linux slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb microsoft simplifi downgrad vista xp want go today besid dept post zonk friday june escapenumb escapenumb escapenumb microsoft http slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb drug prevent cell suicid mitochondria never love dept post zonk friday june escapenumb escapenumb escapenumb biotech http scienc slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb russia claim larg chunk north pole also santa clau dept post zonk friday june escapenumb escapenumb escapenumb almighti buck http scienc slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb amd announc august releas date barcelona chip love dept post zonk friday june escapenumb escapenumb escapenumb amd http hardwar slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb googl map interact rout madison seattl way alaska surprisingli short dept post zonk friday june escapenumb escapenumb escapenumb googl http slashdot org articl pl sid escapenumb escapenumb escapenumb escapenumb copyright escapenumb escapenumb ostg right reserv receiv messag subscrib slashdot stop receiv messag slashdot add messag chang prefer pleas go user page http slashdot org messag log chang prefer',
 'order top result list search engin need qualifi compani qualif googl yahoo msn sever compani like see websit qualifi better posit repli contact info web address usual respons come coupl day review sincer eugen jamison websit posit servic w th st columbu oh unsubscrib list send line unsubscrib linux kernel bodi messag majordomo vger kernel org majordomo info http vger kernel org majordomo info html pleas read faq http www tux org lkml',
 'author jerri date escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb tue escapenumb apr escapenumb new revis escapenumb websvn http websvn samba org cgi bin viewcv cgi view rev root samba doc rev escapenumb log add doc idmap ad schema mode modifi trunk manpag escapenumb idmap ad escapenumb xml changeset modifi trunk manpag escapenumb idmap ad escapenumb xml trunk manpag escapenumb idmap ad escapenumb xml escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb utc rev escapenumb trunk manpag escapenumb idmap ad escapenumb xml escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb utc rev escapenumb escapenumb escapenumb escapenumb escapenumb local remot defin id schema mode rfcescapenumb sfu defin schema idmap ad use queri activ directori reghard user group inform either rfcescapenumb schema support includ window escapenumb rescapenumb servic unix sfu schema',
 'one promot take advantag lookup alvncurr escapenumb escapenumb escapenumb day target price escapelong steadili climb top short term bullish insid buy alert alvn releas hot news check catchal call brocker right',
 'canadianpharmaci dedic provid high qualiti medic help achiev better health canadianpharmaci one onlin store realli care reput afraid scam http yearoth hk one know problem absolut confidenti secur purchas',
 'tue escapenumb jun escapenumb spime wrote window version design packag moment updat chang r escapenumb escapenumb escapenumb would faq except stop ask soon thoma frank e harrel jr wrote spime wrote find help thread calcul bic hosmer lemeshow statist logist regress model use glm logist fit see design packag lrm function residu lrm better gof test frank e harrel jr professor chair school medicin depart biostatist vanderbilt univers r help stat math ethz ch mail list http stat ethz ch mailman listinfo r help pleas read post guid http www r project org post guid html provid comment minim self contain reproduc code view messag context http www nabbl com bic hosmer lemeshow statist logist regress tfescapenumb html aescapenumb sent r help mail list archiv nabbl com r help stat math ethz ch mail list http stat ethz ch mailman listinfo r help pleas read post guid http www r project org post guid html provid comment minim self contain reproduc code thoma lumley assoc professor biostatist tlumley u washington edu univers washington seattl r help stat math ethz ch mail list http stat ethz ch mailman listinfo r help pleas read post guid http www r project org post guid html provid comment minim self contain reproduc code',
 'johann hann wrote sunday escapenumb april escapenumb escapenumb escapenumb simo wrote sun escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb johann hann wrote current obviou way explicitli set winbind separ \\\\ smb conf even wors default given man page smb conf wrong tri winbind separ \\\\\\\\ tri escapenumb escapenumb escapelong result actual seper doubl quot \\\\\\\\ result singl quot seem even samba insid fall smb conf pars feel assur extra paragraph smb conf man page explain backslash never treat special way except line continu \\\\\\\\server\\\\shar valid notat singl doubl quot special mean certain keyword e g passdb backend think whole problem symptomat somewhat chaotic handl smb conf option instanc ed plese discuss shadow copi improv need abl liter percent smb conf file standard way work expect char treat variabl substitut certain option e grab alloc sub basic friend obviou indic manpag option get substitut would nice clearli defin standard certain charact meant config file someth work everi option undocu case case basi exampl might escapenumb option must fall one follow type bool valid valu true fals escapenumb escapenumb ye integ valid valu digit string valid valu utf escapenumb char backslash signific list valid valu space delimit string backslash signific indic non break space escap type option list man page escapenumb string list type addit type modifi variabl substitut substitut enabl type interpret liter percent unknown char error caus testparm choke also list man page exampl sure corner case miss think point stand smb conf option standard document code updat work predict case alison',
 'internet sector hot adrenalin nation entertain inc n n major news releas today n n adrenalin nation televis sign affili licens agreement global enetwork provid ecommerc solut itv mediaplex telvo oper system power narrowstep keith dressel start next ventur time pay attent keith record execut respons escapenumb billion record sale person help gener escapenumb gold record escapenumb platinum album escapenumb gold singl hot huge blow mind go read news go check websit new program incred inform within report contain forward look statement within mean section escapenumbera secur act escapenumb section escapenumberb sec act escapenumb statement involv discuss respect project futur event statement histor fact may forward look statement reli make decis past perform never indic futur result expect receiv cash payment acvertis servic near futur amount unknown time un affili third parti may stock sell share without notic report shall constru kind invest advic solicit sym gain momentum see hottest news gem theescapenumb call broker',

In [69]:
## Output feature
y=pd.get_dummies(df['label'])
##give one hot enocoded, we will take ham and where it is ham its 1 and if not its 0
y=y.iloc[:,0].values

In [70]:
#Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(corpus,y,test_size=0.20,random_state=0)

In [71]:
##Creating the TD-IDF Model
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [72]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)
y_pred=spam_detect_model.predict(X_test)

In [73]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
print(score)

0.9464464464464465

In [74]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.96      0.93      0.94       948
        True       0.94      0.96      0.95      1050

    accuracy                           0.95      1998
   macro avg       0.95      0.95      0.95      1998
weighted avg       0.95      0.95      0.95      1998

#Implementing using bag of words

In [75]:
#Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(corpus,y,test_size=0.20,random_state=0)

In [76]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [77]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)
y_pred=spam_detect_model.predict(X_test)

In [78]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
print(score)

0.9354354354354354

In [79]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.91      0.95      0.93       948
        True       0.96      0.92      0.94      1050

    accuracy                           0.94      1998
   macro avg       0.94      0.94      0.94      1998
weighted avg       0.94      0.94      0.94      1998